### ISSUE TITLE
HTTP API?

### ISSUE THREAD

**Issue by yields** [tj/robo#11]
Just a thought, but if robo had http server/api it would be super easy to do `robo -> slack` integration or `robo -> something-else` integration, removing a lot of duplicate code.

Maybe just a `http: true` would include the task in the HTTP API?
Let me know what you think, more than willing to implement that if you think it's a good idea.

**Comment by tj** [comment]
Oops, missed this! I'm weary about it since the interactive interactions w/ cli/http can be so different

**Comment by yields** [comment]
ah forgot about interactivity of it :P, you're right after thinking about this some more it should be something like `http -> (robo, slack, ...)` if anything.

thanks for writing this awesome tool! :)
