### ISSUE TITLE
task specific vars

### ISSUE THREAD

**Issue by tj** [tj/robo#3]
so they're well-defined and defaults are clearly visible without digging into scripts or examples.

**Comment by jtmarmon** [comment]
+1. we have a development repo with a bunch of submodules and a docker compose to control all of them. we have some scripts that we frequently want to apply to a specific running service, but the service name doesn't always come at the end of the command

**Comment by yields** [comment]
Added env vars at https://github.com/tj/robo/pull/26, they're task level, along with https://github.com/tj/robo/pull/28 commands and scripts can have variables.
