### ISSUE TITLE
robo is calling incorrect bash file when absolute paths are used

### ISSUE THREAD

**Issue by iu4u57k3** [tj/robo#35]
This is the robo.yml file:

```bash
bak:
  summary: backup data
  script: /mnt/backup/sh/backup_data.sh
```

when I run `robo bak`,
it prints:

```
error: stat /home/coder/mnt/backup/sh/backup_data.sh: no such file or directory
```

robo must call:
/mnt/backup/sh/backup_data.sh

and not:
 /home/coder/mnt/backup/sh/backup_data.sh

robo is converting all paths to relative path and ignores absolute path

**Comment by yields** [comment]
Appreciate the bug report, sorry for this taking so long, haven't found the time.

[v0.5.5](https://github.com/tj/robo/releases/tag/v0.5.5) contains this fix.
