### ISSUE TITLE
Parallel mode (i.e. concurrently)

### ISSUE THREAD

**Issue by patarapolw** [tj/robo#40]
Concurrently is <https://www.npmjs.com/package/concurrently>. I wonder if there is a Golang version.

**Comment by yields** [comment]
Not sure what you mean, can you elaborate?

If you're looking to run N robo commands in parallel, you can use `xargs` or `parallel`, or that tool you linked.

**Comment by patarapolw** [comment]
> you can use xargs or parallel, or that tool you linked.

Thanks. I'll look into best tools.
