### ISSUE TITLE
pre-command / depends_on?

### ISSUE THREAD

**Issue by patarapolw** [tj/robo#42]
Like, should `robo prebuild` be run before `robo build`? Probably controversial, though.

Although, the concept like hooks might be nice.

Although this can easily be substitute by YAML templating.

**Comment by yields** [comment]
I still didn't find a good enough real use-case for this, however I did need some form of composition of commands, which is kinda similar.

I think composition can achieve what you want, see the example here:
https://github.com/tj/robo/blob/master/_examples/compose/compose.yml

basically `all` would be `build` in your case and it will invoke `robo -c {{ .robo.file }} prebuild`.

Not sure what you're trying to do, but just from the names of your commands it seems like `make` would be a better fit for you.

**Comment by judsona** [comment]
I'm looking for something like this too. 

My use case is we have several build tools i.e ant/gradle for java & make for our C code that are all used by a global project. I would like to be able to trigger each individual build tool whenever i call robo build. 

Essentially I want to use robo as task aggregation tool to handle calling build for each individual project, but would also like the ability to build each thing individually robo buildc, robo buildjava
